package com.tfs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Journey implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String startTime;

   public Journey()
   {
   }

   public java.lang.String getStartTime()
   {
      return this.startTime;
   }

   public void setStartTime(java.lang.String startTime)
   {
      this.startTime = startTime;
   }

   public Journey(java.lang.String startTime)
   {
      this.startTime = startTime;
   }

}